### ISSUE TITLE
Ethernet lights always on

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [getsenic/senic-os#104]
If no cable is plugged, the Ethernet lights are always on. 
I haven't seen much of Ethernet sockets but they usually didn't glow all the time.

Ref. https://www.ibm.com/support/knowledgecenter/ST3FR7_7.8.0/com.ibm.storwize.v7000.780.doc/tbrd_ethports_1914qw.html

Will ask Mylene (Free Electrons) if she can fix it with the tile we have.

**Comment by TheMeaningfulEngineer** [comment]
@calumljohnston @kelada @rudolfs 
This might end up being a minor fix, isn't critical but I think it will be noticed eventually and requested.
In case you feel Mylenes 0.7 days shouldn't be spent on this do take say it.
I'll initiate this on Tuesday.

**Comment by rudolfs** [comment]
👍  more of a bug though, no?

**Comment by kelada** [comment]
👍

**Comment by calumljohnston** [comment]
There's a line in the device tree:
```
&emac { 
       phy-handle = <&int_mii_phy>; 
       phy-mode = "mii"; 
       allwinner,leds-active-low; 
       status = "okay"; 
};
```
Can try changing to `leds-active-high` tomorrow.

**Comment by rudolfs** [comment]
@calumljohnston go for it!

**Comment by TheMeaningfulEngineer** [comment]
@calumljohnston Great suggestion, thanks. 
It's a cheap test I can easily do later. 
Don't feel obliged to do it (unless you really want to) if you have other 
issues.

**Comment by kelada** [comment]
@calumljohnston you fix had no effect on the LEDs unfortunately

**Comment by calumljohnston** [comment]
Have tried adding `allwinner,leds-active-low` as a property to the `int_mii_phy` node as [this](https://groups.google.com/forum/#!topic/linux-sunxi/D3BfrMGbzlk) post seems to imply it may be getting parsed from there.

**Comment by calumljohnston** [comment]
This appears to have worked, but now when I plug in the ethernet cable it breaks itself with the following kernel message:
```[   10.030464] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   10.037007] dwmac-sun8i 1c30000.ethernet eth0: device MAC address f2:2a:d8:0a:c4:12
[   10.046480] Generic PHY 0.1:01: attached PHY driver [Generic PHY] (mii_bus:phy_addr=0.1:01, irq=POLL)
[   10.057817] dwmac-sun8i 1c30000.ethernet eth0: No MAC Management Counters available
[   10.065620] dwmac-sun8i 1c30000.ethernet eth0: PTP not supported by HW
[   10.065998] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
```
