### ISSUE TITLE
Give feedback on factory reset

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [getsenic/senic-os#105]
Been using the factory reset button during the weekend, and it felt a very bad user experience using it.
Would opt for some visual feedback so that you know when it's been pressed and finished.

Suggested feedback:
 * main white led blinks slowly when pressed
 * main white led blinks quickly 3 times once the factory set was applied.

Would ask for a vote on prioritizing this for first batch image. 
There might be quite some factory resets related with those so we should
try to make it more pleasant.

**Comment by TheMeaningfulEngineer** [comment]
The LED is controlled via the device tree at the moment, we would have to switch back to controlling it through an init script and also change the logic of the reset script. I'm afraid there won't be time to make these changes.

**Comment by calumljohnston** [comment]
I would agree that there should be some kind of feedback to the user. Very hard to know when the button has been pressed, let alone when the reset has been applied.

**Comment by calumljohnston** [comment]
Had a thought, can we just tell the device to reboot after the script is done? Would mean the LED turns off for a quite a few seconds but better than nothing imo.

**Comment by TheMeaningfulEngineer** [comment]
@rudolfs 
Any thoughts on Calum's suggestion? Seems like a quick fix that will give at least some visual feedback?

**Comment by rudolfs** [comment]
@calumljohnston, @TheMeaningfulEngineer I don't see why not.

**Comment by rudolfs** [comment]
@kelada Do you have any objections? otherwise I'll just go and change it.

**Comment by kelada** [comment]
@rudolfs no objections this was suggested a while ago and the difference between rebooting and running `supervisorctl restart all` very little. Make the change.
