### ISSUE TITLE
Remove HA related configuration from `production.ini`

### ISSUE THREAD

**Issue by avichalp** [getsenic/senic-os#106]
Following configuration parameters are not used anymore:

- [ ] Remove: `homeassistant_config_path = /data/senic-hub/configuration.yaml`
- [ ] Remove: `homeassistant_api_url = localhost:8123`
- [ ] Replace: from `homeassistant_data_path = /data/senic-hub` to `senic_hub_data_path = /data/senic-hub`

Last one was the misnomer. It has noting to do with HA instead to stores the path where all the config files are stored.

Corresponding application changes are done here: https://github.com/getsenic/senic-hub/pull/413

**Comment by kelada** [comment]
Great! @avichalp I'll add this to my list.

**Comment by kelada** [comment]
https://github.com/getsenic/senic-os/blob/3cb67928a8a06f5693e0098fd11ae6120353694b/meta-senic/recipes-hub/hub-configuration/files/production.ini#L22-L25

@avichalp is it safe to remove lines 22, 23 & 25? or do I need to rename the variable on line 25 to something more appropriate?

**Comment by avichalp** [comment]
@kelada 
Safe to remove: 23 and 25.
Its better to rename 22 to `senic_hub_data_path`.
