### ISSUE TITLE
WiFi does not reconnect after hard reset shortly after connecting to WiFi

### ISSUE THREAD

**Issue by kelada** [getsenic/senic-os#107]
You you connected the hub to wifi using the following command:
`nmcli dev wifi con <ssid> password <pass> ifname wlan0`

And the hard reset it (turn off the power). It will not reconnect to the WiFi network.

However, if you wait a minute or two then hard reset it, it reconnects just fine.

I believe this is a write issue.

**Comment by kelada** [comment]
This issue can be resolved by running:
`nmcli dev wifi con <ssid> password <pass> ifname wlan0 && sync`

The addition of `&& sync` makes sure the data is finishes writing to the disk.

**Note:** this use case is very much a developer one, but it wouldn't hurt to fix this in the WiFi on-boarding code.

@TheMeaningfulEngineer @rudolfs @avichalp

**Comment by rudolfs** [comment]
👍

**Comment by TheMeaningfulEngineer** [comment]
You got a rough impression on the waiting time that you'd stand by behind?

**Comment by kelada** [comment]
I have not profiled this extensively, but it's somewhere between 20 sec > X < 2 min.

Just use the `sync` command and it's fine. Given that the senic-hub backend doesn't actually use the same command it may be unaffected.
