### ISSUE TITLE
Python3 Pydoc is missing

### ISSUE THREAD

**Issue by luminosuslight** [getsenic/senic-os#11]
The module `pydoc` is missing for python3 on senic-os.
It is required by xmlrpc.server which is used for communiation between Netwatch and Bluenet.

I think a solution could be to add it in [meta-senic/recipes-core/images/senic-os.bb](https://github.com/getsenic/senic-os/blob/c7fc16f7d70a70de91b30a0ab2dceb918065da74/meta-senic/recipes-core/images/senic-os.bb#L30).

`Supervisor` works although it alos uses xmlrpc.server because it uses Python 2 where pydoc is available.

**Comment by tomster** [comment]
same here, this has been fixed, but i forgot to reference the issue. thanks for creating it, though!
