### ISSUE TITLE
Python NetworkManager library needs to be added

### ISSUE THREAD

**Issue by luminosuslight** [getsenic/senic-os#12]
For Netwatch and the new version of Bluenet the NetworkManager D-Bus library for Python is required.

It can be installed with 
`/srv/senic_hub/venv/bin/pip3 install --index-url=http://pypi.python.org/simple/ --trusted-host pypi.python.org --no-deps python-networkmanager` 
(`--no-deps` is required because otherwise python-dbus is reinstalled wrongly).

**Important**: in the current release (2.0.1) is a show stopper bug (it is already fixed upstream [here](https://github.com/seveas/python-networkmanager/commit/aea55e82cfd888e12bb4cd7b7c4fffba1a6c09ba)).
It can be fixed by changing line 209 in `/srv/senic_hub/venv/lib/python3.5/site-packages/NetworkManager.py` to:
```        code += "    SignalDispatcher.add_signal_receiver('%s', '%s', self, func, list(args), kwargs)"  % (interface, name)```

(changing `args` -> `list(args)`)

**Comment by tomster** [comment]
thanks for the detailed info. i will make a new senic os release that addresses this on monday

**Comment by tomster** [comment]
this has been done, but i forgot to reference this issue at the time
