### ISSUE TITLE
Allow root ssh access for dev images

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [getsenic/senic-os#120]
The dev images are prompting for passwords and not allowing root access through ssh.
@kelada didn't seem to be experiencing this issue, but it happened for @baali and me.

Am assuming this to be the cause:
https://github.com/getsenic/senic-os/blob/master/meta-senic/recipes-devtools/bootstrap-ansible/files/authorized_keys

The quick workaround is to to uncomment the line `PermitRootLogin yes` from `/etc/ssh/sshd_config`.

**Comment by baali** [comment]
Just tested the changes, can confirm that root is again accessible with `senid-os-dev` over `ssh` :+1:

**Comment by TheMeaningfulEngineer** [comment]
Great, tnx.
Need a confirmation that `senic-os` is not reachable via ssh, before it can be merged.
