### ISSUE TITLE
loggly logs are missing some informations 

### ISSUE THREAD

**Issue by baali** [getsenic/senic-os#135]
With initial results from `0.2.1` RC image, we will need following things to be fixed/improved:

- [ ] Enable the logs for more modules, currently it is just working with `device_discovery`, `netwatch`, `__main__.py` in `nuimo_app`
- [ ] Logs are missing from filesystem, `/data/senic-hub/logs/` this needs to be fixed.
- [ ] To narrow down individual devices, add `cpuid` information to logs.

**Comment by TheMeaningfulEngineer** [comment]
For issues that spawn on multiple repos or are high level user story kind of things please use this repo:
https://github.com/getsenic/dev-board

Got an impression we're aggregating them there for now before doing a test run with the new task/issue tracker. 

@kelada Please correct if didn't get this right.

**Comment by baali** [comment]
Got it. Moving it to dev-board.
