### ISSUE TITLE
Permission issues of Bluenet and Netwatch

### ISSUE THREAD

**Issue by luminosuslight** [getsenic/senic-os#16]
The `senic` user needs access to the D-Bus interface of **BlueZ**. This is already done in [bluetooth.conf](https://github.com/getsenic/senic-os/blob/master/meta-senic/recipes-connectivity/bluez5/bluez5/bluetooth.conf).

In the same way it also needs access to the D-Bus interface of **NetworkManager**. [This file](https://github.com/NetworkManager/NetworkManager/blob/master/src/org.freedesktop.NetworkManager.conf) could be a starting point.

In addition to the D-Bus interfaces, permission to call **`btmgmt bredr off`** on the commandline is also required.

**Comment by TheMeaningfulEngineer** [comment]
Don't know what it is, but has been merged pull request related to it.
Closing.
