### ISSUE TITLE
WiFi interface is sometimes not raised during boot because driver interface registration is delayed

### ISSUE THREAD

**Issue by AravinthPanch** [getsenic/senic-os#2]
**Solution**
- Change the runlevel of network init

**Bootlog**
- INIT: Entering runlevel: 5
- Configuring network interfaces... ip: RTNETLINK answers: File exists
- Failed to bring up lo.
- [    3.301690] mt7601u 1-1:1.0: Warning: unsupported EEPROM version 0d
- [    3.307995] mt7601u 1-1:1.0: EEPROM ver:0d fae:00
- Successfully initialized wpa_supplicant
- rfkill: Cannot open RFKILL control device
- Could not read interface wlan0 flags: No such device
- nl80211: Driver does not support authentication/association or connect commands
- nl80211: deinit ifname=wlan0 disabled_11b_rates=0
- **Could not read interface wlan0 flags: No such device**
- wlan0: Failed to initialize driver interface
- udhcpc: SIOCGIFINDEX: No such device
- Failed to bring up wlan0.
- Starting system message bus: **[    3.572004] usbcore: registered new interface driver mt7601u**
- dbus.
- Starting OpenBSD Secure Shell server: sshd
- done.
- Starting rpcbind daemon...done.
- Starting bluetooth

**Comment by tomster** [comment]
i'm pretty sure that this has become obsolete since we've migrated to using networkmanager.

at any rate i haven't noticed this error during the past weeks
