### ISSUE TITLE
Python 3.5.2 doesn't come with built-in asyncio lib

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/senic-os#23]
The build scripts needs to adopted to include asyncio lib of Python 3.5.2 (the Python version we are using).

For now we install asyncio through ploy when installing Home Assistant (HA), because HA needs an asyncio that matches our Python version.

To copy only `asyncio` into the Senic Hub, run `bin/ploy configure beta -t asyncio` from the `deployment` folder of `senic-hub`.

When this issue is fixed then the ansible task to copy that lib can be removed from here:

https://github.com/getsenic/senic-hub/blob/master/deployment/roles/hub-hass/handlers/main.yml
https://github.com/getsenic/senic-hub/tree/master/deployment/roles/hub-hass/files/asyncio

**Comment by tomster** [comment]
fixed in baec40e60b1cc32deb813ca0fe7a5745d3b99666
