### ISSUE TITLE
SSH root login possible without password of SSH keys

### ISSUE THREAD

**Issue by rudolfs** [getsenic/senic-os#32]
At least on the beta build.

**Comment by tomster** [comment]
i still want to perform a counter check using the production build  before closing this issue but otherwise this is expected behaviour for a development image AFAIK

**Comment by tomster** [comment]
i've double checked this and this is indeed the documented and expected behaviour of a debug image of `DISTRO_TYPE` set to `debug` (which we do inside `senic-dev.conf`
