### ISSUE TITLE
Hub frequently de-authenticating from WiFi

### ISSUE THREAD

**Issue by neelotpalnag** [getsenic/senic-os#38]
The hub gets disconnected from the WiFi even when sitting idle. The report log says:

`[73386.925580] wlan0: deauthenticating from 06:8d:db:18:26:0b by local choice (Reason: 3=DEAUTH_LEAVING)`

I have to reconnect using the `nmcli' command, or using the mobile app.
I reckon the office router might be ending connection to the hub at times of high traffic, since a high number of devices are connected to the "senic-net" access point. Is it a good idea to test the behaviour using my mobile phone as router (with low traffic) ?

**Comment by tomster** [comment]
+1 on testing in different environments, i.e. with different routers.

i will take a device home and leave it on over night, for example

**Comment by neelotpalnag** [comment]
Great! I've done the testing in my apartment, and everything looks great. It hasn't come up since we split the office network. We can close this issue.
