### ISSUE TITLE
Create sysctl.conf in Senic-os [Avahi][systemd]

### ISSUE THREAD

**Issue by neelotpalnag** [getsenic/senic-os#58]
The current Senic-os doesn't have a default `sysctl.conf` for pre-defining `systemd` values.
The ArchLinux website states:
` Note: From version 207 and 21x, systemd only applies settings from /etc/sysctl.d/*.conf and /usr/lib/sysctl.d/*.conf. If you had customized /etc/sysctl.conf, you need to rename it as /etc/sysctl.d/99-sysctl.conf. If you had e.g. /etc/sysctl.d/foo, you need to rename it to /etc/sysctl.d/foo.conf`

**Comment by neelotpalnag** [comment]
*INFO* : To fix the `avahi-daemon` (which runs _zeroconf_) on the Senic OS, follow theses steps: 

Run the following commands:
`sysctl -w net.ipv4.igmp_max_memberships=20`
`sysctl -w net.ipv4.igmp_max_msf=10`
[These values will be reset to 0 after reboot]
Add your _zeroconf_ name in `/etc/avahi/avahi-daemon.conf`, by uncommenting the 
`[server]`
`#host-name=foo`
`#domain-name=local`
and adding your own hostname.

Then, restart avahi-daemon using `systemctl restart avahi-daemon`. Now you can make calls your hub's api backend using `foo.local:6543/-/` or access the lighttpd server at `foo.local:80`.
[Meanwhile, I'm adding the corrections to the Senic OS, so that it becomes a permanent fix]

**Comment by TheMeaningfulEngineer** [comment]
`systemctl status avahi-daemon`

The daemon is running on the new os.
We can revisit it when implementing the feature that relies on avahi.
