### ISSUE TITLE
Getting Ethernet to work.

### ISSUE THREAD

**Issue by baali** [getsenic/senic-os#65]
Our `defconfig` has relevant config line to enable ethernet:

    CONFIG_SUN4I_EMAC=y

but listing network interfaces using `ifconfig -a` doesn't list Ethernet.

**Comment by TheMeaningfulEngineer** [comment]
It seems that even the bootloader doesn't recognize any Ethernet.
Perhaps that is causing the causing it not to be available later.

```
U-Boot 2017.03 (Oct 11 2017 - 13:38:59 +0200) Allwinner Technology

CPU:   Allwinner H3 (SUN8I 1680)
Model: Senic Hub
DRAM:  256 MiB
MMC:   SUNXI SD/MMC: 0
*** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Net:   No ethernet found.
```

**Comment by calumljohnston** [comment]
[sun8i-emac](http://linux-sunxi.org/Sun8i_emac) seems to have been dropped in favour of dwmac-sun8i. Will try configuring this driver and adding to the dts.

**Comment by baali** [comment]
With PR #85 this seems to be resolved and working.

**Comment by TheMeaningfulEngineer** [comment]
Fixed with: https://github.com/getsenic/senic-os/pull/85
