### ISSUE TITLE
Senic Hub application stack needs to be ported to Rocko

### ISSUE THREAD

**Issue by kelada** [getsenic/senic-os#73]
Currently the Senic Hub application stack does not work after upgrading the OS to Rocko.

The following error is thrown after entering the WiFi password via the frontend.

```
root@senic-hub:~# tail -f /data/senic-hub/logs/bluenet.log
  File "/usr/lib/python3.5/site-packages/NetworkManager.py", line 77, in handle_signal
    receiver(sender, *(sargs + rargs), **rkwargs)
TypeError: on_state_changed() missing 1 required positional argument: 'nm_state'
2017-12-20 00:01:56,352 ERROR [dbus.connection] Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/NetworkManager.py", line 77, in handle_signal
    receiver(sender, *(sargs + rargs), **rkwargs)
TypeError: on_state_changed() missing 1 required positional argument: 'nm_state'
```

We appear to use a [fork](https://github.com/getsenic/python-networkmanager) of `python-networkmanager`, however this fork is no different from what I can tell to the [original repo](https://github.com/seveas/python-networkmanager). Based on the error message I think the issues is with `dbus` in SenicOS rather than this particular python package.

**Comment by TheMeaningfulEngineer** [comment]
Can you translate it into a `curl` command so I can reproduce it easily?

**Comment by kelada** [comment]
The setup procedure is a series of specially ordered, timed and non-atomic commands. It is quicker to just use the app, that is my recommendation.

**Comment by TheMeaningfulEngineer** [comment]
To reproduce the error:

* kill the mobile app
* clear the mobile app cache
* turn on/off wifi and bt
* on the hub run `senic_hub_factory_reset`
* reset the hub
* turn on wifi/bt
* turn on the app
* proceed with standard onboarding

**Comment by TheMeaningfulEngineer** [comment]
**Current assumption**

The error is happening on the bluenet side on the method [on_state_changed](https://github.com/getsenic/senic-hub/blob/master/senic_hub/bluenet/bluenet.py#L190). 
That is a callback function registered in NetworkManager through dbus.

**Comment by avichalp** [comment]
@TheMeaningfulEngineer 's discarded assumptions makes sense to me.
With `NetworkManager V1.4` the callback in not called with the correct arguments.
The 2nd argument is not passed instead the useful information is present in `kwargs`.
A proposed solution could be in this PR:
https://github.com/getsenic/senic-hub/pull/393

**Comment by TheMeaningfulEngineer** [comment]
Resolved with: 
https://github.com/getsenic/senic-os/commit/e2835734bd234ee0005ca69b0203c295d7779535

Which is this change in the senichub code:
https://github.com/getsenic/senic-hub/commit/01fd5bd8725add5e73d3cc35a169f0dc837daefa
