### ISSUE TITLE
Add hardware testing scripts

### ISSUE THREAD

**Issue by kelada** [getsenic/senic-os#77]
The goal of the functional testing is to look for hardware (manufacturing) faults in the carrier PCB, Nano Pi Neo, BT and WiFi.

- [x] Device boots
- [x] LED
- [x] Hardware reset button
- [x] Wifi (via USB 1) - see PR: https://github.com/getsenic/senic-os/pull/78
  - [x] Scan
  - [x] Connect
  - [x] Send/Receive data
  - [x] Disconnect
- [x] Bluetooth (via UART) - see PR: https://github.com/getsenic/senic-os/pull/89
  - [x] Scan
  - [x] Pair
  - [x] Send/Receive data
  - [x] Disconnect
- [ ] USB 2 (external port, empty by default)
  - [ ] Use an additional bluetooth or wifi dongle to perform a similar test as above

All tests should pass and then print out the identity of the devices to the screen. See `Product serialization` document in company cloud storage.

**Comment by baali** [comment]
There are some shell based tests available in `meta-senic/recipes-core/initscripts/initscripts/esd_test.sh`, I will start with them as reference.

**Comment by kelada** [comment]
I'm not convinced that any of those work given that we've moved to systemd, can you confirm if these work?

Additionally, the idea for the hardware testing script is that once the device has booted we can type a command eg. `test` and it will check all the hardware and output a QR code of the identity of the device. This only needs to be run during assembly or potentially to diagnose hardware issues.

**Comment by baali** [comment]
Using [unittests](https://docs.python.org/3/library/unittest.html) and running tests covering above mentioned modules and in the end combining the unique serial code along with test results to create a [QR Code](https://github.com/mnooner256/pyqrcode)?

**Comment by rudolfs** [comment]
The esd_test.sh is remains from when Aravinth still worked here, I guess it was used for ESD testing, not production related. I think we can safely assume that all of the scripts will need to be written from scratch.

**Comment by baali** [comment]
The recipe for [qrencode](https://layers.openembedded.org/layerindex/recipe/39323/) package to generate QRCode from string has a flag(`--without-tools`) for disabling the `qrencode` binary tool to be built. I tried to put together recipe for their latest v4.0.0 release but it still needs some work to package the binary and lib files.

**Comment by TheMeaningfulEngineer** [comment]
@kelada @avichalp 
The scripts seem to be working good enough.
Can we close this and open more specific issues once we see what could be improved through usage?
