### ISSUE TITLE
Disable Ethernet on boot

### ISSUE THREAD

**Issue by kelada** [getsenic/senic-os#90]
Currently our implementation does not handle Ethernet very well, for now we will disable it via something like systemd.

**Comment by TheMeaningfulEngineer** [comment]
I've been experiencing random popping of Ethernet, can't relate it to a reason.
It seems to be consistent after restarts for an image from [this build](https://github.com/getsenic/senic-os/tree/8e974ca0e4a8ab8a73b40d994b9ab8de83fe1159) which doesn't involve any Ethernet related changes, [the recipe](https://github.com/getsenic/senic-os/tree/8e974ca0e4a8ab8a73b40d994b9ab8de83fe1159/meta-senic/recipes-connectivity/networkmanager) is there.
But I've seen it come an go with different images.

You're addressing this in netwatch so this won't be an OS issue any more?

**Comment by kelada** [comment]
What do you mean by "popping"?

I'm working on a PR to allow ethernet to be enabled by default, but have it not effect the hubs on boarding process.

**Comment by TheMeaningfulEngineer** [comment]
> What do you mean by "popping"?

Listed with `ifconfig`  and working when you plug in the cable.
Can you reference it here so we can then not worry about this issue actively.

**Comment by kelada** [comment]
Here is the issue: https://github.com/getsenic/senic-hub/issues/409
