### ISSUE TITLE
Senic OS security

### ISSUE THREAD

**Issue by rudolfs** [getsenic/senic-os#93]
- [x] Remove/disable ssh server
- ~~Either set a password for root and/or remove the ability to login via console tty~~

**Comment by kelada** [comment]
I prose the following security improvements.

- Remove/disable ssh server
- Either set a password for `root` and/or remove the ability to login via console tty
- Migrate all applications to run as normal users
- Set appropriate file permissions for sensitive files

**Comment by TheMeaningfulEngineer** [comment]
Would extend with:
* Remove unnecessary apps
* Check iptable rules

Won't be making this for Tuesday, though due to https://github.com/getsenic/senic-hub/issues/408
